"""Initial database schema

Revision ID: aefdda780fdc
Revises: 
Create Date: 2026-03-01 13:30:04.553683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aefdda780fdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dive_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('max_depth', sa.Float(), nullable=True),
    sa.Column('water_type', sa.String(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('marine_life_highlights', sa.Text(), nullable=True),
    sa.Column('best_season', sa.String(), nullable=True),
    sa.Column('certification_required', sa.String(), nullable=True),
    sa.Column('average_visibility', sa.Float(), nullable=True),
    sa.Column('current_strength', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dive_sites_id'), 'dive_sites', ['id'], unique=False)
    op.create_index(op.f('ix_dive_sites_name'), 'dive_sites', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('certification_level', sa.String(), nullable=True),
    sa.Column('total_dives', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('saved_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_cost_estimate', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_trips_id'), 'saved_trips', ['id'], unique=False)
    op.create_table('transit_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_site_id', sa.Integer(), nullable=False),
    sa.Column('to_site_id', sa.Integer(), nullable=False),
    sa.Column('transport_type', sa.String(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('travel_time_hours', sa.Float(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('departure_times', sa.Text(), nullable=True),
    sa.Column('arrival_times', sa.Text(), nullable=True),
    sa.Column('restrictions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_site_id'], ['dive_sites.id'], ),
    sa.ForeignKeyConstraint(['to_site_id'], ['dive_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_routes_id'), 'transit_routes', ['id'], unique=False)
    op.create_table('transit_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('transit_route_id', sa.Integer(), nullable=False),
    sa.Column('planned_departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booking_reference', sa.String(), nullable=True),
    sa.Column('cost_actual', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['transit_route_id'], ['transit_routes.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['saved_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_plans_id'), 'transit_plans', ['id'], unique=False)
    op.create_table('trip_dives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('dive_site_id', sa.Integer(), nullable=False),
    sa.Column('dive_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dive_time', sa.Time(), nullable=False),
    sa.Column('max_depth_planned', sa.Float(), nullable=True),
    sa.Column('bottom_time_planned', sa.Integer(), nullable=True),
    sa.Column('dive_type', sa.String(), nullable=True),
    sa.Column('equipment_needed', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dive_site_id'], ['dive_sites.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['saved_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_dives_id'), 'trip_dives', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_dives_id'), table_name='trip_dives')
    op.drop_table('trip_dives')
    op.drop_index(op.f('ix_transit_plans_id'), table_name='transit_plans')
    op.drop_table('transit_plans')
    op.drop_index(op.f('ix_transit_routes_id'), table_name='transit_routes')
    op.drop_table('transit_routes')
    op.drop_index(op.f('ix_saved_trips_id'), table_name='saved_trips')
    op.drop_table('saved_trips')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dive_sites_name'), table_name='dive_sites')
    op.drop_index(op.f('ix_dive_sites_id'), table_name='dive_sites')
    op.drop_table('dive_sites')
    # ### end Alembic commands ###
